### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by erathorn** [evolaemp/online_cognacy_ident#3]
We should go for python 3.5 or so. Currently, an installation of `python-igraph ` under any version of windows is not possible for python 3.6.

**Comment by LinguList** [comment]
somehow, I ran into an igraph issue here on my 3.5 version, so I had to resort to UPGMA. No idea why. But there may be some update to igraph, which would also mean that changing the igraph-cluster code is in order.

**Comment by pavelsof** [comment]
@erathorn, did the binaries from the link you added to the README fix the problem for 3.6? I guess that providing the helpful link is as much as we can do unless we can replace the package with another one.

@LinguList, I remember having issues installing igraph on my last laptop running Ubuntu 14.04 (but I do not have problems now on 16.04).. but unfortunately I do not remember how I fixed them back then (if I did at all).

**Comment by erathorn** [comment]
The last time I checked, there were no igraph binaries for python 3.6. This was the main reason for me to suggest using python 3.5. If I remember correctly, there were also some problems for other dependencies with python 3.6.

**Comment by PhyloStar** [comment]
I am using 3.5 with igraph. All is well as of now. :)

**Comment by pavelsof** [comment]
What about adding this clarification at the very end of the `windows users` paragraph: (but even those might not work with Python 3.6 and you might need to use Python 3.5 instead).

The alternatives would be to use another package or implement the InfoMap algorithm ourselves.

**Comment by LinguList** [comment]
my bug is resolved now. It was my stupidity, as we have tests not passed on lingpy via travis, as they'd require too many dependencies, so I only spotted it when really using it, but it's solved now.

**Comment by erathorn** [comment]
@LinguList So igraph on 3.5 works for you?

**Comment by LinguList** [comment]
yes, all works fine on ubuntu and archlinux.

**Comment by erathorn** [comment]
@pavelsof If there are no functionalities in the code which are available under 3.6 but not 3.5 we can stick to 3.6. Otherwise, I would suggest changing the Python version to 3.5

**Comment by pavelsof** [comment]
I am also using 3.5 on my machine just because this is the default on Ubuntu. However, if somebody has 3.6 (e.g. Mattis on his Arch Linux should have that by default) and they do not have issues installing igraph, we should not restrict them. In other words, we can say that we have been using Python 3.5 but we should not say that users must use 3.5 because chances are that the restriction would be unnecessary (e.g. if Mattis was to strictly follow our instructions, he would have to go through the hassle of manually building Python 3.5).

What about adding that sentence at the very beginning of the setup section:
The code is developed using Python 3.5 but later versions should also do as long as the dependencies are satisfied.
...and leave the windows users paragraph as it is now?

**Comment by erathorn** [comment]
Good idea!

**Comment by pavelsof** [comment]
Done with 3f2e4587df3677a18001671e510bbe2e4f23b6ab :)

**Comment by LinguList** [comment]
What Robert usually is doing is saying: this code was tested in machine X with version Y, etc., and (and this is also important): if you use this code and run into difficulties, make sure you try and run it in a fresh virtual environment (this avoids people coming with personal bugs)

**Comment by pavelsof** [comment]
I am not sure about the former but I like the latter and added it with 67e52f4bd683eab0842fda006786e22d5d7def89 :)
